### ISSUE TITLE
Tool Stopped Working

### ISSUE THREAD

**Issue by Anonymous42456** [gerarreal/Project-M-Cosmetics-Generator#2]
The tool doesn't generate any of the cosmetics anymore. When I open the software, all it does is open CMD and display "001 Mario", then it closes itself without generating a single name cosmetic. I've tried running the program as an admin, rebooting my PC, and disabling my antivirus, but it still didn't work.

![Screenshot 2023-12-03 195633](https://github.com/gerarreal/Project-M-Cosmetics-Generator/assets/20717186/98d68ddd-bd63-47a0-8e35-60d41e757867)

**Comment by gerarreal** [comment]
Did you erase any files from the .zip? It should look something like this.
![image](https://github.com/gerarreal/Project-M-Cosmetics-Generator/assets/79531765/5e87c9f1-a13d-4ec6-aaaf-984c3be629ea)

**Comment by Anonymous42456** [comment]
> Did you erase any files from the .zip? It should look something like this. ![image](https://private-user-images.githubusercontent.com/79531765/287616956-5e87c9f1-a13d-4ec6-aaaf-984c3be629ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2OTg1MjAsIm5iZiI6MTcwMTY5ODIyMCwicGF0aCI6Ii83OTUzMTc2NS8yODc2MTY5NTYtNWU4N2M5ZjEtYTEzZC00ZWM2LWFhYWYtOTg0YzNiZTYyOWVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA0VDEzNTcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkZmU2ZjNhM2MzYTJmNDBhMGI5YjJjNGZhNTUwMDUxYTk2MjBiZWZlZWE4MmJiZmU2MTliNTVjZjE4MDUwZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4P9HQa0e0PbuZL9MrD9G_taVKdz3OOeCAuSuuARxkoA)

I didn't delete any files. I've tried re-downloading the .zip, but I got the same results.

**Comment by Anonymous42456** [comment]
Never mind, the cosmetic generator is working now! Thank you for the help! ^-^
